language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-28
licenses:
  - 'build-tools;28.0.3'
  - 'Android SDK Build-Tools 28.0.3'
addons:
  sonarcloud:
    organization: "dionrats-github"
before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-28 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  ./gradlew connectedAndroidTest
#script:
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
